// ==============================================================================
// Module:      tb_fir
// Description: Testbench for simple_fir.
//              Reads 'input_data.txt', feeds it to the DUT, and logs output.
// ==============================================================================

module tb_fir;

    // --- Testbench Signals ---
    // These connect to the DUT (Device Under Test)
    logic clk;
    logic rst_n;
    logic valid_in;
    logic signed [7:0] data_in;
    logic valid_out;
    logic signed [7:0] data_out;
    
    // --- File Handling Variables ---
    integer file_handle; // Pointer to the open file
    integer scan_status; // Result of the read operation (EOF check)
    integer out_val;     // Temporary variable to hold value read from file
    
    // --- DUT Instantiation ---
    // Connect the testbench signals to the module ports
    simple_fir u_fir (
        .clk(clk),
        .rst_n(rst_n),
        .valid_in(valid_in),
        .data_in(data_in),
        .valid_out(valid_out),
        .data_out(data_out)
    );
    
    // --- Clock Generation ---
    // Create a 100 MHz Clock (Period = 10ns)
    initial begin
        clk = 0;
        forever #5 clk = ~clk; // Toggle every 5ns
    end
    
    // --- Waveform Setup (SimVision/Xcelium specific) ---
    initial begin
        // Open a waveform database named "waves.shm"
        $shm_open("waves.shm");
        // "AS" = Record All Signals in all Scopes (Hierarchy)
        $shm_probe("AS"); 
    end
    
    // --- Main Test Process ---
    initial begin
        // 1. Initialization
        // Start with reset active (low) and inputs quiet
        rst_n = 0;
        valid_in = 0;
        data_in = 0;
        
        // Open the stimulus file generated by MATLAB
        file_handle = $fopen("input_data.txt", "r");
        
        // Safety check: Did the file open?
        if (file_handle == 0) begin
            $display("ERROR: Could not open input_data.txt. Did you run MATLAB?");
            $finish;
        end
        
        // 2. Reset Sequence
        $display("Applying Reset...");
        #20 rst_n = 1; // Release reset after 20ns
        #10;           // Wait a bit
        
        // 3. Stimulus Loop
        // Keep reading until we reach End of File (EOF)
        while (!$feof(file_handle)) begin
            
            // Read one integer from the file
            scan_status = $fscanf(file_handle, "%d\n", out_val);
            
            // If we successfully read a number (scan_status == 1)
            if (scan_status == 1) begin
                
                // Synchronize with the clock
                @(posedge clk); 
                
                // Drive the inputs
                valid_in <= 1;
                data_in  <= out_val[7:0]; // Cast integer to 8-bit
                
            end else begin
                valid_in <= 0;
            end
        end
        
        // 4. End of Test
        @(posedge clk);
        valid_in <= 0; // Stop sending valid data
        
        // Wait 100ns to allow the pipeline to flush/drain
        #100;
        
        // Close file and exit
        $fclose(file_handle);
        $display("--------------------------------------------------");
        $display("Simulation Finished Successfully.");
        $display("Check waves.shm or console output for results.");
        $display("--------------------------------------------------");
        $finish; // Stop simulation
    end
    
    // --- Output Monitor ---
    // Print the result to the console whenever the filter outputs valid data
    always @(posedge clk) begin
        if (valid_out) begin
            // %t prints simulation time, %d prints decimal
            $display("Time: %t | Output: %d", $time, data_out);
        end
    end

endmodule